export const SYSTEM_PERMISSIONS = [
  {
    key: "admin.panel.access",
    description: "Access admin panel UI routes.",
  },
  {
    key: "dashboard.read",
    description: "Read dashboard analytics and summary views.",
  },
  {
    key: "users.read",
    description: "Read user lists and user details.",
  },
  {
    key: "users.manage",
    description: "Create, update, delete users and reset user password.",
  },
  {
    key: "roles.manage",
    description: "Create/update roles and assign permissions.",
  },
  {
    key: "products.manage",
    description: "Manage products, variants, and product metadata.",
  },
  {
    key: "inventory.manage",
    description: "Manage stock, inventory logs, and warehouse stock movement.",
  },
  {
    key: "orders.read_all",
    description: "Read all orders across customers.",
  },
  {
    key: "orders.read_own",
    description: "Read own orders only.",
  },
  {
    key: "orders.update",
    description: "Update order status/payment metadata.",
  },
  {
    key: "shipments.manage",
    description: "Create/update/delete shipment records and sync couriers.",
  },
  {
    key: "blogs.manage",
    description: "Create/update/delete blogs.",
  },
  {
    key: "newsletter.manage",
    description: "Manage newsletter and subscriber operations.",
  },
  {
    key: "coupons.manage",
    description: "Create/update/delete coupons and coupon settings.",
  },
  {
    key: "settings.manage",
    description: "Access settings areas with elevated configuration privileges.",
  },
  {
    key: "settings.banner.manage",
    description: "Manage homepage and promotional banners.",
  },
  {
    key: "settings.payment.manage",
    description: "Manage payment settings and methods.",
  },
  {
    key: "settings.shipping.manage",
    description: "Manage shipping rates and shipping configuration.",
  },
  {
    key: "settings.vat.manage",
    description: "Manage VAT class and VAT rate configuration.",
  },
  {
    key: "settings.courier.manage",
    description: "Manage courier configuration.",
  },
  {
    key: "settings.warehouse.manage",
    description: "Manage warehouse configuration.",
  },
  {
    key: "settings.activitylog.read",
    description: "Read admin activity logs based on allowed scope.",
  },
  {
    key: "chats.manage",
    description: "Read/respond/assign/close all support chats.",
  },
  {
    key: "chats.respond",
    description: "Respond as customer in own support chats.",
  },
  {
    key: "reports.read",
    description: "Read financial and operational reports.",
  },
  {
    key: "profile.manage",
    description: "Manage own account profile and password.",
  },
  {
    key: "storefront.access",
    description: "Access storefront buyer experience.",
  },
  {
    key: "cart.manage",
    description: "Manage own cart.",
  },
  {
    key: "wishlist.manage",
    description: "Manage own wishlist.",
  },
  {
    key: "logistics.manage",
    description: "Manage logistics operations and coordination.",
  },
  {
    key: "payroll.manage",
    description: "Manage payroll and employee compensation.",
  },
  {
    key: "delivery-men.manage",
    description: "Onboard and manage delivery personnel.",
  },
  {
    key: "scm.access",
    description: "Access the supply chain management module.",
  },
  {
    key: "suppliers.read",
    description: "Read supplier directories and supplier details.",
  },
  {
    key: "suppliers.manage",
    description: "Create and update supplier records.",
  },
  {
    key: "supplier_performance.read",
    description: "Read supplier lead-time intelligence, on-time delivery trends, and reliability scorecards.",
  },
  {
    key: "sla.read",
    description: "Read supplier SLA policies, SLA scorecards, and breach history.",
  },
  {
    key: "sla.manage",
    description: "Create/update supplier SLA policies and run SLA breach evaluations.",
  },
  {
    key: "sla.dispute.resolve",
    description: "Resolve or reject supplier SLA disputes with governance notes.",
  },
  {
    key: "sla.termination.approve",
    description: "Approve/reject/execute supplier SLA termination governance cases.",
  },
  {
    key: "sla.notifications.manage",
    description: "Trigger and manage supplier SLA escalation notifications.",
  },
  {
    key: "purchase_requisitions.read",
    description: "Read purchase requisitions and requisition line items.",
  },
  {
    key: "purchase_requisitions.manage",
    description: "Create, update, submit, and convert purchase requisitions within allowed scope.",
  },
  {
    key: "purchase_requisitions.approve",
    description: "Approve or reject submitted purchase requisitions.",
  },
  {
    key: "purchase_orders.read",
    description: "Read purchase orders and their line items.",
  },
  {
    key: "purchase_orders.manage",
    description: "Create and update purchase orders.",
  },
  {
    key: "purchase_orders.approve",
    description: "Approve submitted purchase orders.",
  },
  {
    key: "goods_receipts.read",
    description: "Read goods receipt history and receipt details.",
  },
  {
    key: "goods_receipts.manage",
    description: "Receive goods and post stock from approved purchase orders.",
  },
  {
    key: "supplier_returns.read",
    description: "Read supplier return requests, dispatches, and closure history.",
  },
  {
    key: "supplier_returns.manage",
    description: "Create, update, submit, and dispatch supplier returns within allowed scope.",
  },
  {
    key: "supplier_returns.approve",
    description: "Approve or close supplier returns and post supplier credit adjustments.",
  },
  {
    key: "replenishment.read",
    description: "Read replenishment rules, stock planning signals, and recommendation queues.",
  },
  {
    key: "replenishment.manage",
    description: "Manage replenishment rules and generate replenishment requisitions within allowed scope.",
  },
  {
    key: "supplier_ledger.read",
    description: "Read supplier ledger balances, invoices, payments, and statements.",
  },
  {
    key: "supplier_invoices.read",
    description: "Read supplier invoices and invoice aging.",
  },
  {
    key: "supplier_invoices.manage",
    description: "Create and manage supplier invoices posted to accounts payable.",
  },
  {
    key: "supplier_payments.read",
    description: "Read supplier payment history and allocations.",
  },
  {
    key: "supplier_payments.manage",
    description: "Create supplier payments and reduce payable balances.",
  },
  {
    key: "supplier_payments.override_hold",
    description: "Override SLA/AP payment holds on supplier invoices with mandatory justification.",
  },
  {
    key: "three_way_match.read",
    description: "Review three-way match results between purchase orders, receipts, and supplier invoices.",
  },
  {
    key: "warehouse_transfers.read",
    description: "Read warehouse transfer requests, dispatches, and receipts.",
  },
  {
    key: "warehouse_transfers.manage",
    description: "Create, dispatch, receive, and update warehouse transfers within assigned scope.",
  },
  {
    key: "warehouse_transfers.approve",
    description: "Approve submitted warehouse transfer requests before dispatch.",
  },
  {
    key: "delivery.dashboard.access",
    description: "Access delivery-man assignment and operational dashboard flows.",
  },
] as const;

export type PermissionKey = (typeof SYSTEM_PERMISSIONS)[number]["key"];

const ALL_PERMISSION_KEYS = SYSTEM_PERMISSIONS.map((permission) => permission.key);

export const SYSTEM_ROLE_DEFINITIONS: Array<{
  name: string;
  label: string;
  description: string;
  immutable: boolean;
  permissions: PermissionKey[];
}> = [
  {
    name: "superadmin",
    label: "Super Admin",
    description: "System owner role with unrestricted access.",
    immutable: true,
    permissions: [...ALL_PERMISSION_KEYS],
  },
  {
    name: "admin",
    label: "Admin",
    description: "Full operational admin role.",
    immutable: false,
    permissions: [...ALL_PERMISSION_KEYS],
  },
  {
    name: "support",
    label: "Support Agent",
    description: "Customer support and order visibility role.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "orders.read_all",
      "chats.manage",
      "chats.respond",
      "profile.manage",
    ],
  },
  {
    name: "catalog",
    label: "Catalog Manager",
    description: "Product and inventory management role.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "products.manage",
      "inventory.manage",
      "profile.manage",
    ],
  },
  {
    name: "logistics",
    label: "Logistics",
    description: "Shipment and operational logistics role.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "orders.read_all",
      "shipments.manage",
      "logistics.manage",
      "settings.shipping.manage",
      "settings.courier.manage",
      "settings.warehouse.manage",
      "profile.manage",
    ],
  },
  {
    name: "content",
    label: "Content Manager",
    description: "Blog/newsletter/banner operations.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "blogs.manage",
      "newsletter.manage",
      "settings.banner.manage",
      "profile.manage",
    ],
  },
  {
    name: "finance",
    label: "Finance Manager",
    description: "Finance and reporting focused role.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "orders.read_all",
      "orders.update",
      "coupons.manage",
      "reports.read",
      "profile.manage",
    ],
  },
  {
    name: "hr",
    label: "HR Manager",
    description: "Human resources and payroll management role.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "users.read",
      "users.manage",
      "payroll.manage",
      "profile.manage",
    ],
  },
  {
    name: "delivery_man",
    label: "Delivery Man",
    description: "Delivery execution role for assigned shipment handling.",
    immutable: false,
    permissions: [
      "delivery.dashboard.access",
      "profile.manage",
    ],
  },
  {
    name: "scm_admin",
    label: "SCM Admin",
    description: "Full supply chain administration across suppliers, purchase orders, and receipts.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "suppliers.read",
      "suppliers.manage",
      "supplier_performance.read",
      "sla.read",
      "sla.manage",
      "sla.dispute.resolve",
      "sla.termination.approve",
      "sla.notifications.manage",
      "purchase_requisitions.read",
      "purchase_requisitions.manage",
      "purchase_requisitions.approve",
      "purchase_orders.read",
      "purchase_orders.manage",
      "purchase_orders.approve",
      "goods_receipts.read",
      "goods_receipts.manage",
      "supplier_returns.read",
      "supplier_returns.manage",
      "supplier_returns.approve",
      "replenishment.read",
      "replenishment.manage",
      "supplier_ledger.read",
      "supplier_invoices.read",
      "supplier_invoices.manage",
      "supplier_payments.read",
      "supplier_payments.manage",
      "supplier_payments.override_hold",
      "three_way_match.read",
      "warehouse_transfers.read",
      "warehouse_transfers.manage",
      "warehouse_transfers.approve",
      "profile.manage",
    ],
  },
  {
    name: "procurement_manager",
    label: "Procurement Manager",
    description: "Manage suppliers and purchase orders, including approvals.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "suppliers.read",
      "suppliers.manage",
      "supplier_performance.read",
      "sla.read",
      "sla.manage",
      "sla.dispute.resolve",
      "sla.termination.approve",
      "sla.notifications.manage",
      "purchase_requisitions.read",
      "purchase_requisitions.manage",
      "purchase_requisitions.approve",
      "purchase_orders.read",
      "purchase_orders.manage",
      "purchase_orders.approve",
      "goods_receipts.read",
      "supplier_returns.read",
      "supplier_returns.manage",
      "supplier_returns.approve",
      "replenishment.read",
      "replenishment.manage",
      "supplier_ledger.read",
      "supplier_invoices.read",
      "supplier_invoices.manage",
      "three_way_match.read",
      "warehouse_transfers.read",
      "warehouse_transfers.manage",
      "warehouse_transfers.approve",
      "profile.manage",
    ],
  },
  {
    name: "warehouse_receiver",
    label: "Warehouse Receiver",
    description: "Receive stock from approved purchase orders into assigned warehouses.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "purchase_orders.read",
      "goods_receipts.read",
      "goods_receipts.manage",
      "supplier_returns.read",
      "supplier_returns.manage",
      "replenishment.read",
      "replenishment.manage",
      "warehouse_transfers.read",
      "warehouse_transfers.manage",
      "warehouse_transfers.approve",
      "profile.manage",
    ],
  },
  {
    name: "procurement_requestor",
    label: "Procurement Requestor",
    description: "Raise and submit warehouse purchase requisitions for procurement review.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "purchase_requisitions.read",
      "purchase_requisitions.manage",
      "profile.manage",
    ],
  },
  {
    name: "warehouse_transfer_manager",
    label: "Warehouse Transfer Manager",
    description: "Manage and approve stock transfers between warehouses.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "inventory.manage",
      "warehouse_transfers.read",
      "warehouse_transfers.manage",
      "warehouse_transfers.approve",
      "supplier_returns.read",
      "supplier_returns.manage",
      "supplier_returns.approve",
      "replenishment.read",
      "replenishment.manage",
      "supplier_ledger.read",
      "supplier_invoices.read",
      "three_way_match.read",
      "profile.manage",
    ],
  },
  {
    name: "replenishment_planner",
    label: "Replenishment Planner",
    description: "Monitor warehouse demand signals and raise replenishment requisitions from planning suggestions.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "inventory.manage",
      "purchase_requisitions.read",
      "purchase_requisitions.manage",
      "purchase_orders.read",
      "warehouse_transfers.read",
      "replenishment.read",
      "replenishment.manage",
      "profile.manage",
    ],
  },
  {
    name: "supplier_return_manager",
    label: "Supplier Return Manager",
    description: "Control supplier return approval, dispatch, and accounts payable adjustment flows.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "purchase_orders.read",
      "goods_receipts.read",
      "supplier_returns.read",
      "supplier_returns.manage",
      "supplier_returns.approve",
      "supplier_ledger.read",
      "supplier_invoices.read",
      "three_way_match.read",
      "profile.manage",
    ],
  },
  {
    name: "ap_manager",
    label: "AP Manager",
    description: "Accounts payable role for supplier invoices, payments, and ledger visibility.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "suppliers.read",
      "supplier_performance.read",
      "sla.read",
      "sla.notifications.manage",
      "supplier_ledger.read",
      "supplier_invoices.read",
      "supplier_invoices.manage",
      "supplier_payments.read",
      "supplier_payments.manage",
      "supplier_payments.override_hold",
      "three_way_match.read",
      "reports.read",
      "profile.manage",
    ],
  },
  {
    name: "sla_manager",
    label: "SLA Manager",
    description: "Own supplier SLA targets and evaluate supplier breach trends.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "suppliers.read",
      "supplier_performance.read",
      "sla.read",
      "sla.manage",
      "sla.dispute.resolve",
      "sla.termination.approve",
      "sla.notifications.manage",
      "purchase_orders.read",
      "goods_receipts.read",
      "reports.read",
      "profile.manage",
    ],
  },
  {
    name: "supplier_performance_analyst",
    label: "Supplier Performance Analyst",
    description: "Review supplier lead-time reliability, late-order risk, and delivery performance trends.",
    immutable: false,
    permissions: [
      "admin.panel.access",
      "dashboard.read",
      "scm.access",
      "suppliers.read",
      "supplier_performance.read",
      "sla.read",
      "purchase_orders.read",
      "goods_receipts.read",
      "reports.read",
      "profile.manage",
    ],
  },
];

const ROLE_TEMPLATE_FALLBACKS = Object.fromEntries(
  SYSTEM_ROLE_DEFINITIONS.map((definition) => [definition.name, [...definition.permissions]]),
) as Record<string, PermissionKey[]>;

export const LEGACY_ROLE_FALLBACKS: Record<string, PermissionKey[]> = {
  ...ROLE_TEMPLATE_FALLBACKS,
  user: [
    "storefront.access",
    "orders.read_own",
    "profile.manage",
    "cart.manage",
    "wishlist.manage",
    "chats.respond",
  ],
  delivery_man: [
    "delivery.dashboard.access",
    "profile.manage",
  ],
};

export const ADMIN_PANEL_ACCESS_FALLBACK_PERMISSIONS: PermissionKey[] = [
  "dashboard.read",
  "users.read",
  "users.manage",
  "roles.manage",
  "products.manage",
  "inventory.manage",
  "orders.read_all",
  "orders.update",
  "shipments.manage",
  "blogs.manage",
  "newsletter.manage",
  "coupons.manage",
  "settings.manage",
  "settings.banner.manage",
  "settings.payment.manage",
  "settings.shipping.manage",
  "settings.vat.manage",
  "settings.courier.manage",
  "settings.warehouse.manage",
  "settings.activitylog.read",
  "chats.manage",
  "reports.read",
  "scm.access",
  "suppliers.read",
  "suppliers.manage",
  "supplier_performance.read",
  "sla.read",
  "sla.manage",
  "sla.dispute.resolve",
  "sla.termination.approve",
  "sla.notifications.manage",
  "purchase_requisitions.read",
  "purchase_requisitions.manage",
  "purchase_requisitions.approve",
  "purchase_orders.read",
  "purchase_orders.manage",
  "purchase_orders.approve",
  "goods_receipts.read",
  "goods_receipts.manage",
  "supplier_returns.read",
  "supplier_returns.manage",
  "supplier_returns.approve",
  "replenishment.read",
  "replenishment.manage",
  "supplier_ledger.read",
  "supplier_invoices.read",
  "supplier_invoices.manage",
  "supplier_payments.read",
  "supplier_payments.manage",
  "supplier_payments.override_hold",
  "three_way_match.read",
  "warehouse_transfers.read",
  "warehouse_transfers.manage",
  "warehouse_transfers.approve",
];

export function isPermissionKey(value: string): value is PermissionKey {
  return SYSTEM_PERMISSIONS.some((permission) => permission.key === value);
}

export function getAllPermissionKeys(): PermissionKey[] {
  return [...ALL_PERMISSION_KEYS];
}
