import { daysAgo, daysFromNow } from "./helpers";

export const COUPON_MANAGEMENT_SEED_DATA = [
  {
    code: "WELCOME10",
    discountType: "PERCENTAGE",
    discountValue: 10,
    minOrderValue: 1000,
    maxDiscount: 300,
    usageLimit: 500,
    usedCount: 42,
    isValid: true,
    expiresAt: daysFromNow(60),
  },
  {
    code: "BOE500",
    discountType: "FIXED",
    discountValue: 500,
    minOrderValue: 3500,
    maxDiscount: 500,
    usageLimit: 250,
    usedCount: 18,
    isValid: true,
    expiresAt: daysFromNow(45),
  },
  {
    code: "FREESHIP",
    discountType: "FREE_SHIPPING",
    discountValue: 120,
    minOrderValue: 1500,
    maxDiscount: 120,
    usageLimit: 1000,
    usedCount: 121,
    isValid: true,
    expiresAt: daysFromNow(90),
  },
  {
    code: "EID25",
    discountType: "PERCENTAGE",
    discountValue: 25,
    minOrderValue: 2500,
    maxDiscount: 800,
    usageLimit: 300,
    usedCount: 300,
    isValid: false,
    expiresAt: daysAgo(10),
  },
  {
    code: "VIP1000",
    discountType: "FIXED",
    discountValue: 1000,
    minOrderValue: 8000,
    maxDiscount: 1000,
    usageLimit: 50,
    usedCount: 7,
    isValid: true,
    expiresAt: daysFromNow(120),
  },
] as const;
